### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by Bulua** [anvien/2OIB-for-sEMG-Recognition#1]
您好，我看到了您所写的论文，觉得论文体现了非常好的思想，并下载了论文代码，以下是一些关于代码的问题想向您请教：
（1）发现有些模块缺失：
`from ann.highway_model import CNN1, HighwayCNN1, CNN2, HighwayCNN2, FCN1, HighwayFCN1, FCN2, HighwayFCN2, CNN3, \
    HighwayCNN3, HighwayCNN_18, CNN_18`
`from ann.weighted_highway_model import WeightedHighwayCNN1, WeightedHighwayCNN2, WeightedHighwayFCN1, WeightedHighwayFCN2, WeightedHighwayCNN3
from ann.weighted_highway_model import WeightedHighwayCNN_18`
`from dataloader.ninapro_loader import NinaPro_Dataset`
请问您可以发一下完整的代码吗？万分感谢！😁，这是我的邮箱：2783266620@qq.com

**Comment by zhanganguo** [comment]
很抱歉给您带来的困扰，缺失的模块均已补充上来，请下载查阅。
感谢您对我们工作的关注，谢谢！

**Comment by zhanganguo** [comment]
您好，您的邮件我已经收到，不过我现在在外面有个会议，等我今天晚些时候找下代码发给你。

感谢您对我们工作的兴趣~

 

张安国

 

发件人: ***@***.*** ***@***.***> 代表 Bulua
发送时间: 2022年5月27日 15:53
收件人: zhanganguo/2OIB-for-sEMG-Recognition ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zhanganguo/2OIB-for-sEMG-Recognition] Missing Code (Issue #1)

 

您好，我看到了您所写的论文，觉得论文体现了非常好的思想，并下载了论文代码，以下是一些关于代码的问题想向您请教：
（1）发现有些模块缺失：
from ann.highway_model import CNN1, HighwayCNN1, CNN2, HighwayCNN2, FCN1, HighwayFCN1, FCN2, HighwayFCN2, CNN3, \ HighwayCNN3, HighwayCNN_18, CNN_18
from ann.weighted_highway_model import WeightedHighwayCNN1, WeightedHighwayCNN2, WeightedHighwayFCN1, WeightedHighwayFCN2, WeightedHighwayCNN3 from ann.weighted_highway_model import WeightedHighwayCNN_18
from dataloader.ninapro_loader import NinaPro_Dataset
***@***.*** ***@***.***>
